apiVersion: v1
kind: Pod
metadata:
  name: primehub-other
  labels:
    app: primehub-other
spec:
  containers:
  - image: qrtt1/debug-tools:v0.3
    command:
    - bash
    - -c
    - |
      python3 -mhttp.server 5000
    imagePullPolicy: IfNotPresent
    name: notebook
    ports:
    - containerPort: 5000
      protocol: TCP
    securityContext:
      runAsGroup: 0
      runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: primehub-other
  name: primehub-other
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: primehub-other