apiVersion: v1
kind: Pod
metadata:
  name: primehub-app
  labels:
    app: primehub-app
spec:
  initContainers:
  - image: qrtt1/debug-tools:v0.3
    command:
    - bash
    - -c
    - |
      chmod -R 770 /home/jovyan
      chmod -R 777 /monitoring-utils
      touch /monitoring-utils/create-from-init-container
    imagePullPolicy: IfNotPresent
    name: init
    volumeMounts:
    - mountPath: /home/jovyan
      name: my-disk-1
    - mountPath: /monitoring-utils
      name: monitoring-utils
    securityContext:
      runAsGroup: 0
      runAsUser: 0
  containers:
  - image: qrtt1/debug-tools:v0.3
    command:
    - bash
    - -c
    - |
      ls -alh /monitoring-utils
      ls -alh /monitoring-utils/
      python3 -mhttp.server 5000
    imagePullPolicy: IfNotPresent
    name: notebook
    ports:
    - containerPort: 5000
      protocol: TCP
    securityContext:
      runAsGroup: 0
      runAsUser: 0
    volumeMounts:
    - mountPath: /home/jovyan
      name: my-disk-1
    - mountPath: /monitoring-utils
      name: monitoring-utils
  volumes:
  - name: my-disk-1
    persistentVolumeClaim:
      claimName: my-disk-1
  - emptyDir: {}
    name: monitoring-utils
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-disk-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: microk8s-hostpath